version: '2'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
  
   
     
  node2:
    environment:
      - PEERS=ws://node1:6002
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    links:
      - node1:node1
  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    links:
      - node1:node1
      - node2:node2
   
  # node3:
  #   environment:
  #     - PEERS=ws://node2:6003
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #   - "3003:3001"
  #   links:
  #     - node1:node1
  
